channels:
- conda-forge
dependencies:
- python=3.8.18
- pip<=23.2.1
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - numpy==1.20.1
  - packaging==23.2
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==0.24.1
  - scipy==1.10.1
name: mlflow-env
